#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 The esphome-unni-co2-sniffer contributors
# SPDX-License-Identifier: GPL-3.0-or-later
"""Build and run every shipped UNNI YAML feature variant on ESPHome host.

The generated host YAML is derived mechanically from the real device YAML:
ESP32/network/radio-only top-level blocks are removed, while the complete
co2_monitor_0601 block is retained. This keeps the host matrix tied to the
shipped configurations instead of maintaining five independent copies.
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass
import os
from pathlib import Path
import re
import selectors
import shutil
import subprocess
import sys
import time

ROOT = Path(__file__).resolve().parents[2]
GENERATED_PREFIX = ".host-test-"
PASS_MARKER = "UNNI HOST SELF-TEST PASSED"

VARIANTS = (
    "i2c-sniffer.yaml",
    "i2c-sniffer-debug.yaml",
    "i2c-sniffer-no-ble.yaml",
    "i2c-sniffer-ble-only.yaml",
    "i2c-sniffer-sht43-probe.yaml",
)

# These components either do not exist on host or would test ESP32/network
# behavior rather than the portable UNNI component. logger, esphome and the
# external component declaration are intentionally retained.
REMOVE_TOP_LEVEL = {
    "api",
    "ota",
    "wifi",
    "captive_portal",
    "esp32_ble",
    "esp32",
}

TOP_LEVEL_KEY = re.compile(r"^([a-zA-Z0-9_]+):(?:\s|$)")


def _drop_top_level_blocks(text: str) -> str:
    output: list[str] = []
    dropping = False
    for line in text.splitlines(keepends=True):
        match = TOP_LEVEL_KEY.match(line)
        if match:
            dropping = match.group(1) in REMOVE_TOP_LEVEL
        if not dropping:
            output.append(line)
    return "".join(output)


def _set_logger_debug(text: str) -> str:
    lines = text.splitlines()
    in_logger = False
    for index, line in enumerate(lines):
        if line.startswith("logger:"):
            in_logger = True
            continue
        if in_logger and line and not line.startswith((" ", "#")):
            break
        if in_logger and re.match(r"^  level:\s*", line):
            lines[index] = "  level: DEBUG"
            return "\n".join(lines) + "\n"
    raise RuntimeError("could not force logger.level=DEBUG for host smoke test")


def _host_name(variant: str) -> str:
    return "unni-host-" + variant.removesuffix(".yaml").replace("i2c-sniffer", "base").replace("_", "-")


def _set_host_name(text: str, variant: str) -> str:
    name = _host_name(variant)
    lines = text.splitlines()
    in_esphome = False
    replaced = False
    for index, line in enumerate(lines):
        if line.startswith("esphome:"):
            in_esphome = True
            continue
        if in_esphome and line and not line.startswith((" ", "#")):
            in_esphome = False
        if in_esphome and re.match(r"^  name:\s*", line):
            lines[index] = f"  name: {name}"
            replaced = True
            break
    if not replaced:
        raise RuntimeError(f"{variant}: could not replace esphome.name")
    return "\n".join(lines) + "\n"


@dataclass(frozen=True)
class NativeToolchain:
    compiler: str
    compile_flags: tuple[str, ...]
    description: str


def _yaml_quote(value: str) -> str:
    return '"' + value.replace('\\', '\\\\').replace('"', '\\"') + '"'


def _inject_host_build_flags(text: str, flags: tuple[str, ...]) -> str:
    """Add host-only native toolchain flags to the generated configuration."""
    lines = text.splitlines()
    insert_at = None
    in_esphome = False
    for index, line in enumerate(lines):
        if line.startswith("esphome:"):
            in_esphome = True
            continue
        if in_esphome and line and not line.startswith((" ", "#")):
            insert_at = index
            break
    if insert_at is None:
        insert_at = len(lines)

    block = [
        "  # Native host test toolchain; generated by tests/host/run_host_tests.py.",
        "  build_flags:",
    ]
    block.extend(f"    - {_yaml_quote(flag)}" for flag in flags)
    lines[insert_at:insert_at] = block
    return "\n".join(lines) + "\n"


def _probe_compiler(compiler: str, flags: tuple[str, ...]) -> tuple[bool, str]:
    """Compile a tiny C++20 program with exactly the flags used by host builds."""
    probe = ROOT / ".esphome" / "host-cpp20-probe.cpp"
    binary = ROOT / ".esphome" / "host-cpp20-probe"
    probe.parent.mkdir(parents=True, exist_ok=True)
    probe.write_text(
        "#include <concepts>\n"
        "#include <span>\n"
        "template<std::integral T> constexpr T twice(T v) { return v * 2; }\n"
        "int main() { int a[2] = {1, 2}; std::span<int> s(a); return twice(s[0]) == 2 ? 0 : 1; }\n",
        encoding="utf-8",
    )
    try:
        proc = subprocess.run(
            [compiler, *flags, str(probe), "-o", str(binary)],
            cwd=ROOT,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            check=False,
        )
        if proc.returncode != 0:
            return False, proc.stdout.strip()
        run = subprocess.run(
            [str(binary)],
            cwd=ROOT,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            check=False,
        )
        if run.returncode != 0:
            return False, f"probe binary exited with {run.returncode}: {run.stdout.strip()}"
        return True, ""
    finally:
        probe.unlink(missing_ok=True)
        binary.unlink(missing_ok=True)


def _compiler_version(compiler: str) -> str:
    version = subprocess.run(
        [compiler, "--version"],
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        check=False,
    ).stdout.splitlines()
    return version[0] if version else compiler


def _homebrew_llvm_prefix() -> Path | None:
    brew = shutil.which("brew")
    if not brew:
        return None
    proc = subprocess.run(
        [brew, "--prefix", "llvm"],
        stdout=subprocess.PIPE,
        stderr=subprocess.DEVNULL,
        text=True,
        check=False,
    )
    if proc.returncode != 0:
        return None
    prefix = Path(proc.stdout.strip())
    if not prefix:
        return None
    return prefix


def _select_native_toolchain() -> tuple[NativeToolchain | None, str]:
    """Select a C++20 toolchain and flags usable by PlatformIO native.

    On macOS the compiler and libc++ are deliberately treated as a pair. Some
    Apple Command Line Tools releases accept -std=gnu++20 but ship a libc++ that
    lacks the C++20 concepts used by ESPHome. In that case use Homebrew LLVM's
    libc++ headers and runtime explicitly. The flags returned here are injected
    into the generated ESPHome host YAML, so the preflight and real build use
    the same C++ standard-library selection.
    """
    base_flags = ("-std=gnu++20",)
    diagnostics: list[str] = []

    # Respect an explicit compiler first, but on macOS do not assume that CXX
    # also makes PlatformIO select the matching C++ standard library.
    explicit = os.environ.get("CXX")
    default_compiler = explicit or shutil.which("c++") or shutil.which("clang++") or shutil.which("g++")

    if sys.platform == "darwin":
        brew_prefix = _homebrew_llvm_prefix()
        if brew_prefix is not None:
            brew_compiler = brew_prefix / "bin" / "clang++"
            brew_include = brew_prefix / "include" / "c++" / "v1"
            brew_lib = brew_prefix / "lib" / "c++"
            if brew_compiler.exists() and brew_include.is_dir() and brew_lib.is_dir():
                brew_flags = (
                    "-std=gnu++20",
                    "-nostdinc++",
                    f"-I{brew_include}",
                    f"-L{brew_lib}",
                    f"-Wl,-rpath,{brew_lib}",
                )
                # PlatformIO native may ignore CXX and invoke the system compiler.
                # Therefore validate the exact compiler that PlatformIO is likely to use
                # with Homebrew's libc++ flags first. A modern Apple clang can compile
                # against Homebrew libc++; the important part here is the standard library.
                pio_compiler = shutil.which("c++") or shutil.which("clang++") or str(brew_compiler)
                ok, error = _probe_compiler(pio_compiler, brew_flags)
                if ok:
                    return (
                        NativeToolchain(
                            compiler=pio_compiler,
                            compile_flags=brew_flags,
                            description=(
                                f"{_compiler_version(pio_compiler)} with Homebrew libc++ "
                                f"from {brew_prefix}"
                            ),
                        ),
                        "",
                    )
                diagnostics.append(
                    f"System compiler + Homebrew libc++ probe failed:\n{error}"
                )

                # Also probe Homebrew clang itself. This is useful diagnostic evidence,
                # but we do not rely on CXX alone because PlatformIO/native may still use
                # the system compiler internally.
                ok, error = _probe_compiler(str(brew_compiler), brew_flags)
                if not ok:
                    diagnostics.append(f"Homebrew LLVM probe failed:\n{error}")

        if default_compiler:
            ok, error = _probe_compiler(default_compiler, base_flags)
            if ok:
                return (
                    NativeToolchain(
                        compiler=default_compiler,
                        compile_flags=base_flags,
                        description=_compiler_version(default_compiler),
                    ),
                    "",
                )
            diagnostics.append(f"Apple/default native toolchain probe failed:\n{error}")
    else:
        if default_compiler:
            ok, error = _probe_compiler(default_compiler, base_flags)
            if ok:
                return (
                    NativeToolchain(
                        compiler=default_compiler,
                        compile_flags=base_flags,
                        description=_compiler_version(default_compiler),
                    ),
                    "",
                )
            diagnostics.append(f"Native toolchain probe failed:\n{error}")

    if not default_compiler and sys.platform != "darwin":
        diagnostics.append("no native C++ compiler found (CXX/c++/clang++/g++)")
    return None, "\n\n".join(diagnostics)

def make_host_config(source: Path, toolchain: NativeToolchain) -> Path:
    text = _drop_top_level_blocks(source.read_text(encoding="utf-8"))
    text = _set_host_name(text, source.name)
    text = _set_logger_debug(text)
    text = _inject_host_build_flags(text, toolchain.compile_flags)
    # Host networking is supplied by the OS; no wifi: block is valid/needed.
    text += "\nhost:\n  mac_address: \"02:00:00:00:06:01\"\n"
    generated = ROOT / f"{GENERATED_PREFIX}{source.name}"
    generated.write_text(text, encoding="utf-8")
    return generated


def _run_command(command: list[str], env: dict[str, str]) -> int:
    print("+", " ".join(command), flush=True)
    return subprocess.run(command, cwd=ROOT, env=env, check=False).returncode


def _host_binary_path(variant: str) -> Path:
    name = _host_name(variant)
    return ROOT / ".esphome" / "build" / name / ".pioenvs" / name / "program"


def _run_host_binary(binary: Path, env: dict[str, str], timeout_s: int) -> bool:
    if not binary.is_file():
        print(f"Host binary not found after successful compile: {binary}", file=sys.stderr)
        return False

    command = [str(binary)]
    print("+", " ".join(command), flush=True)
    proc = subprocess.Popen(
        command,
        cwd=ROOT,
        env=env,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        bufsize=1,
    )
    deadline = time.monotonic() + timeout_s
    passed = False
    timed_out = False
    try:
        assert proc.stdout is not None
        selector = selectors.DefaultSelector()
        selector.register(proc.stdout, selectors.EVENT_READ)
        while time.monotonic() < deadline:
            remaining = max(0.0, deadline - time.monotonic())
            events = selector.select(timeout=min(0.25, remaining))
            if events:
                line = proc.stdout.readline()
                if line:
                    print(line, end="", flush=True)
                    if PASS_MARKER in line:
                        passed = True
                        break
            if proc.poll() is not None:
                for line in proc.stdout:
                    print(line, end="", flush=True)
                    if PASS_MARKER in line:
                        passed = True
                break
        if not passed and proc.poll() is None and time.monotonic() >= deadline:
            timed_out = True
    finally:
        if proc.poll() is None:
            proc.terminate()
            try:
                proc.wait(timeout=2)
            except subprocess.TimeoutExpired:
                proc.kill()
                proc.wait(timeout=2)

    if timed_out:
        print(f"Host binary did not emit {PASS_MARKER!r} within {timeout_s}s", file=sys.stderr)
    return passed


def _run_smoke(esphome: str, config: Path, variant: str, env: dict[str, str], timeout_s: int) -> bool:
    # `esphome run` is intentionally interactive and keeps a host target alive
    # indefinitely. For automation, compile first and execute the native binary
    # ourselves so we control its lifetime and output capture.
    if _run_command([esphome, "compile", config.name], env) != 0:
        return False
    return _run_host_binary(_host_binary_path(variant), env, timeout_s)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--mode",
        choices=("config", "compile", "run"),
        default="run",
        help="validate, native-compile, or compile+execute each host variant (default: run)",
    )
    parser.add_argument("--timeout", type=int, default=10, help="runtime seconds to wait for each host self-test marker")
    parser.add_argument("--keep-generated", action="store_true")
    parser.add_argument("--esphome", default=shutil.which("esphome") or "esphome")
    args = parser.parse_args()

    toolchain, toolchain_error = _select_native_toolchain()
    if toolchain is None:
        print("Native compiler preflight failed:", file=sys.stderr)
        if toolchain_error:
            print(toolchain_error, file=sys.stderr)
        print(
            "\nHost tests require a native C++20 compiler and standard library. "
            "On macOS the runner can automatically use Homebrew LLVM's libc++ when "
            "the Apple Command Line Tools libc++ lacks the required C++20 concepts.",
            file=sys.stderr,
        )
        return 2
    print(f"Native compiler preflight: {toolchain.description}", flush=True)
    if len(toolchain.compile_flags) > 1:
        print("Native host build flags:", " ".join(toolchain.compile_flags), flush=True)

    failures: list[str] = []
    generated_files: list[Path] = []
    try:
        for variant in VARIANTS:
            source = ROOT / variant
            if not source.exists():
                failures.append(f"{variant}: source YAML missing")
                continue

            generated = make_host_config(source, toolchain)
            generated_files.append(generated)
            print(f"\n=== {variant} -> host ===", flush=True)

            env = os.environ.copy()
            # ESPHome host supports an isolated preferences directory. Keep test
            # state out of the user's normal host preferences and out of HOME.
            prefd = ROOT / ".esphome" / "host-test-prefs" / source.stem
            prefd.mkdir(parents=True, exist_ok=True)
            env["ESPHOME_PREFDIR"] = str(prefd)

            if args.mode == "config":
                ok = _run_command([args.esphome, "config", generated.name], env) == 0
            elif args.mode == "compile":
                ok = _run_command([args.esphome, "compile", generated.name], env) == 0
            else:
                ok = _run_smoke(args.esphome, generated, variant, env, args.timeout)

            if not ok:
                failures.append(f"{variant}: {args.mode} failed")

        if failures:
            print("\nHost test failures:", file=sys.stderr)
            for failure in failures:
                print(f"  - {failure}", file=sys.stderr)
            return 1

        print(f"\nPASS: all {len(VARIANTS)} YAML variants passed host {args.mode} tests")
        return 0
    finally:
        if not args.keep_generated:
            for generated in generated_files:
                generated.unlink(missing_ok=True)


if __name__ == "__main__":
    raise SystemExit(main())
