#!/usr/bin/env python3

import struct
import sys


def convert(input_file, output_file):
    with open(input_file, "rb") as f:
        data = f.read()

    # Header
    if len(data) < 8:
        raise ValueError("Datei ist zu kurz")

    magic = data[0:4]

    if magic != b"LA01":
        raise ValueError(f"Unbekanntes Format: {magic!r}")

    count = struct.unpack_from("<I", data, 4)[0]

    expected_size = 8 + count * 5

    if len(data) < expected_size:
        raise ValueError(
            f"Datei unvollständig: erwartet {expected_size} Bytes, "
            f"bekommen {len(data)}"
        )

    samples = []

    offset = 8

    for _ in range(count):
        timestamp, value = struct.unpack_from(
            "<IB",
            data,
            offset
        )

        samples.append((timestamp, value))
        offset += 5

    if not samples:
        raise ValueError("Capture enthält keine Samples")

    # ------------------------------------------------------------------
    # VCD schreiben
    #
    # VCD-Zeiteinheit = 1 µs
    # ------------------------------------------------------------------

    with open(output_file, "w") as f:

        f.write("$date\n")
        f.write("    generated by capture2vcd.py\n")
        f.write("$end\n")

        f.write("$version\n")
        f.write("    ESP32 3-channel logic analyzer\n")
        f.write("$end\n")

        f.write("$timescale 1us $end\n")

        f.write("$scope module logic_analyzer $end\n")

        f.write("$var wire 1 ! GPIO40 $end\n")
        f.write("$var wire 1 \" GPIO39 $end\n")
        f.write("$var wire 1 # GPIO38 $end\n")

        f.write("$upscope $end\n")
        f.write("$enddefinitions $end\n")

        # Initialzustand
        first_value = samples[0][1]

        gpio40 = 1 if first_value & 1 else 0
        gpio39 = 1 if first_value & 2 else 0
        gpio38 = 1 if first_value & 4 else 0

        f.write("$dumpvars\n")
        f.write(f"{gpio40}!\n")
        f.write(f"{gpio39}\"\n")
        f.write(f"{gpio38}#\n")
        f.write("$end\n")

        last_value = first_value

        # Änderungen schreiben
        for timestamp, value in samples:

            if value == last_value:
                continue

            f.write(f"#{timestamp}\n")

            if (value & 1) != (last_value & 1):
                f.write(f"{1 if value & 1 else 0}!\n")

            if (value & 2) != (last_value & 2):
                f.write(f"{1 if value & 2 else 0}\"\n")

            if (value & 4) != (last_value & 4):
                f.write(f"{1 if value & 4 else 0}#\n")

            last_value = value

    print(f"Samples : {count}")
    print(f"Duration: {samples[-1][0]} us")
    print(f"Output  : {output_file}")


def main():
    if len(sys.argv) != 3:
        print(
            f"Usage: {sys.argv[0]} INPUT.la OUTPUT.vcd",
            file=sys.stderr
        )
        sys.exit(1)

    try:
        convert(sys.argv[1], sys.argv[2])
    except Exception as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()

