#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 The esphome-unni-co2-sniffer contributors
# SPDX-License-Identifier: GPL-3.0-or-later

import struct
import sys


def convert(input_file, output_file):
    with open(input_file, "rb") as f:
        data = f.read()

    if len(data) < 8:
        raise ValueError("capture is too short")

    magic = data[0:4]
    count = struct.unpack_from("<I", data, 4)[0]
    flags = 0
    initial_value = None

    if magic == b"LA02":
        expected_size = 10 + count * 5
        if len(data) != expected_size:
            raise ValueError(
                f"incomplete LA02 capture: expected {expected_size} bytes, got {len(data)}"
            )
        flags = data[8]
        initial_value = data[9]
        offset = 10
    elif magic == b"LA01":
        # Two historical LA01 variants existed: the original 8-byte header and
        # the later 9-byte header with an overflow flag. Keep both readable.
        if len(data) == 9 + count * 5:
            flags = data[8]
            offset = 9
        elif len(data) == 8 + count * 5:
            offset = 8
        else:
            raise ValueError(
                f"invalid LA01 size for {count} samples: got {len(data)} bytes"
            )
    else:
        raise ValueError(f"unknown capture format: {magic!r}")

    samples = []
    for _ in range(count):
        timestamp, value = struct.unpack_from("<IB", data, offset)
        samples.append((timestamp, value))
        offset += 5

    if not samples:
        raise ValueError("capture contains no samples")

    # LA01 did not retain the state before the first edge. Falling back to the
    # first observed state keeps old captures readable, but LA02 is preferred
    # because it preserves that first transition exactly.
    if initial_value is None:
        initial_value = samples[0][1]

    with open(output_file, "w") as f:
        f.write("$date\n")
        f.write("    generated by capture2vcd.py\n")
        f.write("$end\n")
        f.write("$version\n")
        f.write("    CO2 Monitor 0601 passive I2C capture\n")
        f.write("$end\n")
        f.write("$timescale 1us $end\n")
        f.write("$scope module i2c $end\n")
        f.write('$var wire 1 ! SCL $end\n')
        f.write('$var wire 1 " SDA $end\n')
        f.write("$upscope $end\n")
        f.write("$enddefinitions $end\n")

        scl = 1 if initial_value & 0x01 else 0
        sda = 1 if initial_value & 0x02 else 0
        f.write("$dumpvars\n")
        f.write(f"{scl}!\n")
        f.write(f'{sda}"\n')
        f.write("$end\n")

        last_value = initial_value
        for timestamp, value in samples:
            if value == last_value:
                continue
            f.write(f"#{timestamp}\n")
            if (value & 0x01) != (last_value & 0x01):
                f.write(f"{1 if value & 0x01 else 0}!\n")
            if (value & 0x02) != (last_value & 0x02):
                f.write(f'{1 if value & 0x02 else 0}"\n')
            last_value = value

    print(f"Format  : {magic.decode('ascii')}")
    print(f"Samples : {count}")
    print(f"Duration: {samples[-1][0]} us")
    print(f"Overflow: {'yes' if flags & 0x01 else 'no'}")
    print(f"Output  : {output_file}")


def main():
    if len(sys.argv) != 3:
        print(f"Usage: {sys.argv[0]} INPUT.la OUTPUT.vcd", file=sys.stderr)
        sys.exit(1)

    try:
        convert(sys.argv[1], sys.argv[2])
    except Exception as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
